#!/bin/bash

# Get the directory where this script is located
STRAT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Run the python script and pass all arguments ($@) to it
python3 "$STRAT_DIR/ghostdrive.py" "$@"
